# Assignments for "Lists"

1. Write a code to compute the sum of the two lowest numbers and the two highest numbers in the following list.

        my_list = [34, 56, 76, 45, 2, 12, 67, 98, 37, 54, 66]

In [1]:
my_list = [34, 56, 76, 45, 2, 12, 67, 98, 37, 54, 66]
my_list.sort()
klein_total=my_list[0]+my_list[1]
gros_total=my_list[len(my_list)-2]+my_list[len(my_list)-1]
print(my_list)
print("the sum of the two lowest numbers: ", klein_total)
print("the two highest numbers:",gros_total)

[2, 12, 34, 37, 45, 54, 56, 66, 67, 76, 98]
the sum of the two lowest numbers:  14
the two highest numbers: 174

2. The following two lists contain student names and scores. Write a code that gets the name from the user and prints the score of that student.

        names = ["David", "Michael", "John", "James", "Greg", "Mark", "William", "Richard", "Thomas", "Steven", 
                 "Mary", "Susan", "Maria", "Karen", "Lisa", "Linda", "Donna", "Patricia", "Debra", "Eric"]

        scores = [99, 87, 78, 86, 68, 94, 76, 97, 56, 98, 76, 87, 79, 90, 73, 93, 82, 69, 97, 98]

In [2]:
names = ["David", "Michael", "John", "James", "Greg", "Mark", "William", "Richard", "Thomas", "Steven","Mary", "Susan", "Maria", "Karen", "Lisa", "Linda", "Donna", "Patricia", "Debra", "Eric"]
scores = [99, 87, 78, 86, 68, 94, 76, 97, 56, 98, 76, 87, 79, 90, 73, 93, 82, 69, 97, 98]

for n in names:
  print(n,scores[names.index(n)])

David 99
Michael 87
John 78
James 86
Greg 68
Mark 94
William 76
Richard 97
Thomas 56
Steven 98
Mary 76
Susan 87
Maria 79
Karen 90
Lisa 73
Linda 93
Donna 82
Patricia 69
Debra 97
Eric 98

3. By using the two lists above, what is the maximum score and how many students got that score?

In [3]:
scores.sort()
maximumscore=scores[len(scores)-1]
scores = [99, 87, 78, 86, 68, 94, 76, 97, 56, 98, 76, 87, 79, 90, 73, 93, 82, 69, 97, 98]
print(names[scores.index(maximumscore)])

David

4. We can confuse about how many days a month is. Create a list to handle it. You will have month names and day counts in your list together as a nested list.

In [4]:
monate=[['January',31],['Febuary',28],['March',31],['April',30],['May',31],['June',30],['July',31],['Agust',31],['September',30],['October',31],['November',30], ['December',31]] 
for m in monate:
  print(m)

['January', 31]
['Febuary', 28]
['March', 31]
['April', 30]
['May', 31]
['June', 30]
['July', 31]
['Agust', 31]
['September', 30]
['October', 31]
['November', 30]
['December', 31]

5. Now create lists of months for each season. Get month names and day counts from the list that you create before with slicing. Name the lists with seasons.

In [5]:
spring = monate[2:5]
summer = monate [5:8]
fall =   monate [8:11]
winter = monate[0:2]
winter.insert(0,monate [11])
months_by_season = [spring, summer, fall, winter]
print("Spring Months :",spring)
print("summer Months :",summer)
print("fall Months :",fall)
print("winter Months :",winter)

Spring Months : [['March', 31], ['April', 30], ['May', 31]]
summer Months : [['June', 30], ['July', 31], ['Agust', 31]]
fall Months : [['September', 30], ['October', 31], ['November', 30]]
winter Months : [['December', 31], ['January', 31], ['Febuary', 28]]

6. Finally, from the list in the previous question, calculate how many days the summer season lasts.

In [6]:
b=0
for m in summer:
  t=m[len(m)-1:len(m)]
  t=int(t[0])
  b=b+t
print("Number of days of the summer season lasts: ",b)

Number of days of the summer season lasts:  92