# Assignments for "Loops"

1. Please form a multiplication table from user input.

    Example :

        Enter a number : 6
        6 x 1 = 6                                                               
        6 x 2 = 12                                                              
        6 x 3 = 18                                                              
        6 x 4 = 24                                                              
        6 x 5 = 30                                                              
        6 x 6 = 36                                                              
        6 x 7 = 42                                                              
        6 x 8 = 48                                                              
        6 x 9 = 54                                                              
        6 x 10 = 60

In [ ]:
entry=int(input("Enter a number :"))
for i in range(1,11):
  print(entry,"*", i,"=",entry*i)

Enter a number :2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

[link text](https://)2. Simply by using list compherension, form a list by taking square of odds numbers and by calculating cube of even numbers from 1 to 20. <br><br>

In [ ]:
L1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

odd_sq = []
odd_cube = []

for i in L1:
  if i%2==0:
   continue
  else:
    odd_sq.append(i*i)
    odd_cube.append(i*i*i)


print(even_sq,odd_sq)
print(even_cube,odd_cube)

[] [1, 9, 25, 49, 81, 121, 169, 225, 289, 361]
[] [1, 27, 125, 343, 729, 1331, 2197, 3375, 4913, 6859]

3. Please type a code that inverts the initial user input.

    Example : "automobile" --> "elibomotua"<br><br>

In [ ]:
d

In [ ]:
entry=input("Enter your word   :")
a=""
for i in entry:
   a=i+a
   print(a)

Enter your wordomer
o
mo
emo
remo

4. Using `range(1, 201)`, make two lists. One is containing all even numbers and the other containing all odd numbers.<br><br>

In [ ]:
one=list(range(1,201))
two=list(range(1,201,2))
print(one)
print(two)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]

*5*. Define a function called `count` that has two arguments called `sequence` and `item`. Return the number of times the item occurs in the list.<br>

    Example:
    ```python
    count([1,2,1,1], 1)
    ```
    It should return 3. Because `1` appears 3 times in the list.<br><br>

In [67]:
def count(squence,item):
  c=0
  for a in squence:
    if item==a:
      c+=1
  return c

count([1,1,1,1,2,3,1],1)

5

6. Write a function called `digit_sum` that takes a positive integer n as input and returns the sum of all that number's digits as a single-digit number.

    Example:
        27684 --> 2 + 7 + 6 + 8 + 4 = 27 --> 2 + 7 = 9<br>

In [71]:
def digit_sum(n):
  top=0
  for a in n:
    top=top+int(a)
  return top

digit_sum(input("Enter a digit numbers  :"))

Enter a digit numbers23

5

7. Write a program to find greatest common divisor (GCD) or highest common factor (HCF) of given two numbers.<br><br>

In [72]:
def gcd(a,b): 
      
    if (a == 0): 
        return b 
    if (b == 0): 
        return a 
  
    if (a == b): 
        return a 
  
    if (a > b): 
        return gcd(a-b, b) 
    return gcd(a, b-a) 
  
a=(int(input("Enter number 1")))
b=(int(input("Enter number 2")))
if(gcd(a, b)): 
    print('GCD of', a, 'and', b, 'is', gcd(a, b)) 
else: 
    print('not found')

Enter number 112
Enter number 223
GCD of 12 and 23 is 1

8. Write a Python program that iterates integers from 1 to 50. For multiples of three print `fizz` instead of the number and for the multiples of five print `buzz`. For numbers which are multiples of both three and five print `fizzbuzz`.

In [89]:
example = list(range(1,51))
example2=list(range(1,51))
print(example2)
for i in example:
  if i%3==0 and i%5==0:
    example2[i-1]="fizzbuzz"
  elif i%5==0:
   example2[i-1]="buzz"
  elif i%3==0 :
    example2[i-1]="fizz"
print(example2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
15
30
45
[1, 2, 'fizz', 4, 'buzz', 'fizz', 7, 8, 'fizz', 'buzz', 11, 'fizz', 13, 14, 'fizzbuzz', 16, 17, 'fizz', 19, 'buzz', 'fizz', 22, 23, 'fizz', 'buzz', 26, 'fizz', 28, 29, 'fizzbuzz', 31, 32, 'fizz', 34, 'buzz', 'fizz', 37, 38, 'fizz', 'buzz', 41, 'fizz', 43, 44, 'fizzbuzz', 46, 47, 'fizz', 49, 'buzz']

9. Please form a list out of Fibonacci numbers from 1 to 50. The first two Fibonacci numbers are 1. The next numbers are the sum of the previous two.

In [94]:

nterms = 50
n1, n2 = 0, 1
count = 0

print("Fibonacci sequence:")
while count < nterms:
       print(n1)
       temp = n1 + n2
       n1 = n2
       n2 = temp
       count += 1

Fibonacci sequence:
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049